### ISSUE TITLE
Traffic Estimator sheet doesn't work

### ISSUE THREAD

**Issue by tksohishi** [similarweb/api-tools#1]
It uses wrong(deprecated?) API endpoint: /v1/EstimatedTraffic. It should be replaced with /v1/visits with valid start and end parameters and change the accessor to estTraffic variable in Code.gs.

**Comment by noamsp** [comment]
The endpoint is still valid. We are not exposing 'EstimatedTraffic' in the website anymore becuase we introduced 'visits' which is more flexible. 

However, 'EstimatedTraffic' is still valid for fetching the traffic numbers for the previous month, which is the usecase of the Traffic Estimator.

**Comment by tksohishi** [comment]
Ah, got it. It would be great to rewrite the script with new API and fix the description which are mentioning email addresses, but it's actually working with domains :)
